name: 蓝鲸自动打包机

on:
  push:
    branches: [ "release", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 获取源码及所有核心零件
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: 配置 Java 环境
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: 伪造官方本地配置文件
      run: |
        touch local.properties
        echo "storeFile=dummy" >> local.properties
        echo "storePassword=dummy" >> local.properties
        echo "keyAlias=dummy" >> local.properties
        echo "keyPassword=dummy" >> local.properties

    - name: 激活编译引擎
      run: chmod +x gradlew

    - name: 终极打包手机版和电视版
      run: ./gradlew assembleMobileDebug assembleLeanbackDebug --stacktrace

    - name: 输出并提取 APK 文件
      uses: actions/upload-artifact@v4
      with:
        name: 蓝鲸影院-专属版APP
        path: app/build/outputs/apk/**/*.apk
